# Generated by Django 5.0.1 on 2024-08-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='no user', max_length=255, null=True)),
                ('prodName', models.CharField(max_length=255)),
                ('prodPrix', models.CharField(max_length=255)),
                ('poids', models.CharField(max_length=255)),
                ('qts', models.CharField(max_length=255)),
                ('userName', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ref', models.CharField(default=3501867, max_length=255)),
                ('codeBar', models.ImageField(blank=True, upload_to='codeBarCmmd/')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
    ]
