# Generated by Django 5.0.1 on 2024-08-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='ref',
            field=models.CharField(default=4303880, max_length=255),
        ),
    ]
