# Generated by Django 5.0.1 on 2024-08-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_alter_commande_ref_alter_commande_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='poids',
        ),
        migrations.AlterField(
            model_name='commande',
            name='ref',
            field=models.CharField(default=7420329, max_length=255),
        ),
    ]
