# Generated by Django 5.0.1 on 2024-08-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_alter_commande_prodname_alter_commande_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='annuler',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commande',
            name='ref',
            field=models.CharField(default=4784824, max_length=255),
        ),
    ]
