# Generated by Django 5.0.1 on 2024-08-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_commande_annuler_alter_commande_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='ref',
            field=models.CharField(default=2520738, max_length=255),
        ),
    ]
