# Generated by Django 5.0.1 on 2024-08-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_alter_commande_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='ref',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
