# Generated by Django 5.0.1 on 2024-07-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='images',
            field=models.ImageField(max_length=5, upload_to='images/'),
        ),
    ]
