# Generated by Django 5.0.1 on 2024-07-29 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_produit_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='images',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='prix',
        ),
        migrations.AddField(
            model_name='produit',
            name='images_five',
            field=models.ImageField(default=datetime.datetime(2024, 7, 29, 14, 26, 46, 482681, tzinfo=datetime.timezone.utc), upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='images_four',
            field=models.ImageField(default=datetime.datetime(2024, 7, 29, 14, 28, 9, 627985, tzinfo=datetime.timezone.utc), upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='images_one',
            field=models.ImageField(default=datetime.datetime(2024, 7, 29, 14, 28, 35, 722958, tzinfo=datetime.timezone.utc), upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='images_to',
            field=models.ImageField(default=datetime.datetime(2024, 7, 29, 14, 28, 57, 497968, tzinfo=datetime.timezone.utc), upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='images_tree',
            field=models.ImageField(default=datetime.datetime(2024, 7, 29, 14, 29, 13, 792757, tzinfo=datetime.timezone.utc), upload_to='images/'),
            preserve_default=False,
        ),
    ]
