# Generated by Django 5.0.1 on 2024-07-29 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_produit_images_remove_produit_prix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(default=datetime.datetime(2024, 7, 29, 17, 47, 10, 258523, tzinfo=datetime.timezone.utc), max_length=1000),
            preserve_default=False,
        ),
    ]
